package com.example.quranapp.core.debug

enum class PipelineStageType {
    ALARM_SCHEDULED,
    RECEIVER_STARTED,
    FOREGROUND_SERVICE_REQUESTED,
    FOREGROUND_SERVICE_STARTED,
    FOREGROUND_NOTIFICATION_SHOWN,
    FOREGROUND_NOTIFICATION_REMOVED,
    NOTIFICATION_SHOWN,
    NOTIFICATION_SUPPRESSED,
    NOTIFICATION_BLOCKED_PERMISSION,
    ADHAN_PLAYBACK_STARTED,
    ADHAN_PLAYBACK_COMPLETED,
    WAKE_LOCK_ACQUIRED,
    PIPELINE_COMPLETED,
    PIPELINE_FAILED,
    FOREGROUND_START_FAILED
}
